name = "SupabaseAuth"
uuid = "a0444c1d-6bfd-4346-a8b3-2f7d58af6057"
version = "0.1.0"
authors = ["Sujan Das <iamsujandas2007@gmail.com>"]

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
HTTP = "1.10.19"
JSON3 = "1.14.3"
